#!/bin/bash
#!/data/data/com.termux/files/usr/bin/bash
#I love my country Indonesia
#autoinstaller DWIPANTARA
#coded MR.R3DH3T feat loopstr34k
#Don't copyright and recode this script bro

#Warna // Color
blue='\e[0;34m'
cyan='\e[0;36m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'

#Bar
function spinner()
{
     sleep 3 &
     PID=$!
     i=1
     sp="/-\|"
     echo -n ' '
     while [ -d /proc/$PID ]
     do
       printf "\b${sp:i++%${#sp}:1}"
     done
}
#Checking Internet Connection
clear
echo -e "${yellow}Checking Internet Connection"
spinner
function checkinternet() 
{
  ping -t 50 -c 1 google.com > /dev/null 2>&1
  if [[ "$?" != 0 ]]
  then
    echo -e $yellow "${red}NOT CONNECTED"
    echo
    echo -e $red "Run this Script, if you Connected to Internet"
    echo
    echo -e $red "Exit!"
    echo && sleep 2
    exit
  else
    echo -e $yellow "${okegreen}CONNECTED"
  fi
}
checkinternet
sleep 3
clear

####################################################
# CTRL C
####################################################
trap ctrl_c INT
ctrl_c () {
clear
echo -e $cyan" Terima Kasih Sudah Memakai Tools DWIPANTARA "
sleep 2
echo ""
echo -e $cyan" Dunia Itu Hanya Sesaat, Jadi Berbuatlah Baik Untuk Akhiratmu "
sleep 2
echo ""
echo -e $cyan" ├─   DWIPANTARA   ─┤" 
echo -e $cyan" ├─   Instagram    ─┤"
echo -e $cyan"         └─> dwi_pantara0518"
sleep 0.5
echo -e $cyan" ├─    Website     ─┤"
echo -e $cyan"         └─> https://dwipantara0518.blogspot.com/ "
sleep 1
echo -e $cyan" ├─     Author     ─┤ "
echo -e $cyan" ├─    MR.R3DH3T   ─┤ " 
echo -e $cyan" ├─    Instagram   ─┤ "
echo -e $cyan"          └─> /naufalziidane_ and loopstr34k "
echo " "
echo -e $white" +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ "
echo -e $white" | 1.MsLq | 2.Ksatria Mujahidin | 3.mv24ky | 4.farhan | 5.root-S4D       | "
echo -e $white" | 6.greenhorn | 7.sasman96 | 8.mizuki | 9.nyi_iteung_ | 10.H Code       | "
echo -e $white" | 11.hanum_zaahra | 12.pribumi_jihad | 13.Lokzy | 14.Nc_tesla199        | "
echo -e $white" | 15.Opposite6890 | 16.B0C4HTU4N4K4L | 17.loopstr34k | 18.Emak_Julia    | "
echo -e $white" | 19.pasukan_hitam | 20.Niqabies_women | 21.A | 22._mushab_bin_umair    | "
echo -e $white" | 23.Hidayat | 24.farhan | 25.Dani | 26.rezim_laknat | 27.Squad_monkey3 | "
echo -e $white" | 28.p417ger4n_bers0rb4n | 29.d_dev05 | 30.Mr.Cl4Y | 31.jurnal_jamaah   | "
echo -e $white" +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ "
echo ""
sleep 2
read enter
exit
}


echo -e $red"   ______        _____ ____   _    _   _ _____  _    ____      _ "
echo -e $red"  |  _ \ \      / /_ _|  _ \ / \  | \ | |_   _|/ \  |  _ \    / \ "
echo -e $red"  | | | \ \ /\ / / | || |_) / _ \ |  \| | | | / _ \ | |_) |  / _ \ "
echo -e $red"  | |_| |\ V  V /  | ||  __/ ___ \| |\  | | |/ ___ \|  _ <  / ___ \ "
echo -e $red"  |____/  \_/\_/  |___|_| /_/   \_\_| \_| |_/_/   \_\_| \_\/_/   \_\ "
echo ""
echo -e $white"        ___ _   _ ____   ___  _   _ _____ ____ ___    _ "
echo -e $white"       |_ _| \ | |  _ \ / _ \| \ | | ____/ ___|_ _|  / \ "
echo -e $white"        | ||  \| | | | | | | |  \| |  _| \___ \| |  / _ \ "
echo -e $white"        | || |\  | |_| | |_| | |\  | |___ ___) | | / ___ \ "
echo -e $white"       |___|_| \_|____/ \___/|_| \_|_____|____/___/_/   \_\ "
echo ""
sleep 2
echo -e $lightgreen"   >> Select Tools For Install << "
echo ""
echo -e $red"   [ 01 ] Metasploit Framework "
sleep 0.3
echo -e $red"   [ 02 ] Torshammer "
sleep 0.3
echo -e $red"   [ 03 ] Xerxes "
sleep 0.3
echo -e $red"   [ 04 ] SQLmap "
sleep 0.3
echo -e $red"   [ 05 ] Termux Ohmyzsh for theme "
sleep 0.3
echo -e $red"   [ 06 ] ko-dork for scann vuln web "
sleep 0.3
echo -e $red"   [ 07 ] CMS Scamner "
sleep 0.3
echo -e $red"   [ 08 ] Ngrok "
sleep 0.3
echo -e $red"   [ 09 ] Webdav "
sleep 0.3
echo -e $red"   [ 10 ] venom for Backdor "
sleep 0.3
echo -e $red"   [ 11 ] Shell-Finder "
sleep 0.3
echo -e $red"   [ 12 ] Sudo for Install venom "
sleep 0.3
echo -e $white"   [ 13 ] RED_HAWK "
sleep 0.3
echo -e $white"   [ 14 ] Kali NetHunter "
sleep 0.3
echo -e $white"   [ 15 ] hasher "
sleep 0.3
echo -e $white"   [ 16 ] weeman for phising "
sleep 0.3
echo -e $white"   [ 17 ] Mrcakil "
sleep 0.3
echo -e $white"   [ 18 ] SpazSms "
sleep 0.3
echo -e $white"   [ 19 ] Websploit "
sleep 0.3
echo -e $white"   [ 20 ] Script deface Creator "
sleep 0.3
echo -e $white"   [ 21 ] fsociety "
sleep 0.3
echo -e $white"   [ 22 ] Virus "
sleep 0.3
echo -e $white"   [ 23 ] IPGeolocation "
sleep 0.3
echo -e $white"   [ 24 ] Instagram brute "
sleep 0.3
echo -e $green"   [ 00 ] Exit "
echo ""
echo -e $white""
read -p" root@dwipantara ~/# " dwipan;

if [ $dwipan = 1 ] || [ $dwipan = 01 ]
then
clear
echo -e $blue" [ Installing Metasploit ] "
sleep 1
apt update && apt upgrade
echo " Harus Sabar! "
sleep 3
pkg install curl
curl -LO https://raw.githubusercontent.com/Hax4us/Metasploit_termux/master/metasploit.sh
chmod +x metasploit.sh
./metasploit.sh
sleep 5
mv metasploit-framework $HOME
echo "${green} Use Command 'msfconsole' to run metasploit "
echo "${green} e.g: root@dwipantara#~/ msfconsole"
sleep 2
echo -e $red" { Done Install bro } "
fi


if [ $dwipan = 0 ] || [ $dwipan = 00 ] 
then
clear
echo -e $okegreen">>  Pesan terakhir! << "
echo ""
echo ""
sleep 2
echo -e $lightgreen" Jangan pernah tinggalin ngaji ingat! menuntut ilmu agama itu wajib , karna jaman sekarang orang islam tidak tahu agamanya sendiri "
echo ""
sleep 3
echo -e $red" Jangan pacaran mulu! , Jika kamu diam saat agamamu dihina gantilah pakaianmu dengan kain kafan "
echo ""
sleep 3
echo -e $red" Islam bagaikan buih di lautan ( Banyak orang islam tapi tidak tahu islam yang sesungguhnya ) "
echo ""
sleep 3
echo -e $okegreen" Semangat Berjuang Demi Membela Kebenaran! TAKBIR! " 
echo ""
sleep 3
echo -e $lightgreen" Saling memaafkan sesama sodara , wa alfu minkum wassalamu'alaikum warrohmatullohi wabarokatuhu "
echo ""
sleep 3
fi

if [ $dwipan = 2 ] || [ $dwipan = 02 ]
then 
clear
echo -e $blue" [ Installing Torshammer ] "
apt-get update && apt-get upgrade 
apt-get install git
apt install python 
apt install python2
git clone https://github.com/cyweb/hammer.git
cd hammer
chmod +x hammer.py
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 3 ] || [ $dwipan = 03 ]
then
clear
echo -e $blue" [ Installing Xerxes ] "
apt-get update && apt-get upgrade -y
apt-get install git -y
apt install clang -y
git clone https://github.com/zanyarjamal/xerxes.git
cd xerxes
clang xerxes.c -o xerxes
echo " use ?  ./xerxes target (ex) https://www.suaranasional.com 80 , jika tidak ada tulisan voly sent ulang aja bro "
echo ""
echo ""
sleep 2
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 4 ] || [ $dwipan = 04 ] 
then
clear
echo -$blue" [ Installing SQLmap-dev ] "
apt-get update && apt-get upgrade
apt-get install git 
git clone --depth 1 https://github.com/sqlmapproject/sqlmap.git sqlmap-dev
cd sqlmap-dev
chmod +x *.py
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 5 ] || [ $dwipan = 05 ]
then
clear
echo -e $blue" [ Installing Termux-ohmyzsh ] "
apt-get update && apt-get upgrade
pkg install curl
sh -c "$(curl -fsSL https://github.com/Cabbagec/termux-ohmyzsh/raw/master/install.sh)"
~/.termux/colors.sh
echo -e $white" ganti color ? ketik ~/.termux/colors.sh "
sleep 2
echo ""
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 6 ] || [ $dwipan = 06 ]
then
clear
echo -e $blue" [ Installing ko-dork ] "
apt-get update && apt-get upgrade
apt-get install git
apt install python
apt install python2
git clone https://github.com/ciku370/ko-dork.git
mv ko-dork $HOME
cd ~/
cd ko-dork
chmod +x *.py
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 7 ] || [ $dwipan = 07 ]
then
clear
echo -e $blue" [ Installing CMS scanner ] "
apt-get update && apt-get upgrade
pkg install python
apt-get install git
git clone https://github.com/Dionach/CMSmap.git
sleep 1
cd CMSmap
chmod +x cmsmap.py
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 8 ] || [ $dwipan = 08 ]
then
clear
echo -e $red" [ Installing Ngrok ] "
apt-get update && apt-get upgrade 
apt install wget
mkdir ngrok
cd ~/ngrok
echo -e "${red} (1) 32 bit"
echo -e "${red} (2) 64 bit"
echo -e "${red} (3) ARM"
read -p " root@dwipantara#~/ngrok-installer/ " ngrok;
  if [ $ngrok = 1 ] || [ $ngrok = 01 ]
  then
  echo $yellow"Download Ngrok 32 bit "
  wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip
  unzip ngrok-stable-linux-386.zip
  echo $yellow"Use Command './ngrok http 80' to use Ngrok"
  echo $yellow"e.g: root@dwipantara#~/ ngrok http 80"
  exit
  fi
  if [ $ngrok = 2 ] || [ $ngrok = 02 ]
  then
  echo $yellow"Download Ngrok 64 bit "
  wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
  unzip ngrok-stable-linux-amd64.zip
  echo $yellow"Use Command './ngrok http 80' to use Ngrok"
  echo $yellow"e.g: root@dwipantara#~/ ngrok http 80"
  exit
  fi
  if [ $ngrok = 3 ] || [ $ngrok = 03 ]
  then
  echo "Download Ngrok ARM "
  wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip
  unzip ngrok-stable-linux-arm.zip
  echo $yellow"Use Command './ngrok http 80' to use Ngrok"
  echo $yellow"e.g: root@dwipantara#~/ ngrok http 80"
  exit
  fi

cd ~/
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 9 ] || [ $dwipan = 09 ] 
then
clear
echo -e $blue" [ Installing Webdav ] "
apt update && apt upgrade
apt install python2
pip2 install urllib3 chardet certifi idna requests
apt install openssl curl
pkg install libcurl
mkdir webdav
cd ~/webdav
wget https://pastebin.com/raw/HnVyQPtR -O webdav.py
chmod 777 webdav.py
cd ~/
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 10 ] || [ $dwipan = 010 ] 
then
clear
echo -e $blue" [ Installing venom ] "
sleep 2
apt-get install git 
git clone https://github.com/r00t-3xp10it/venom.git
cd venom
sudo chmod -R +x *.sh
sudo chmod -R +x *.py
cd aux
sudo ./setup.sh
echo -e $white" install metasploit dulu bro error kan "
sleep 2
echo ""
echo -e $white" if you run main tools , use msfvenom -h "
sleep 3
echo ""
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 11 ] || [ $dwipan = 011 ]
then
clear
echo -e $blue" [ Installing Shell-finder ] "
apt-get update && apt-get upgrade 
apt-get install git 
apt install python2 
https://github.com/bhavyanshu/Shell-Finder.git
cd Shell-Finder
chmod +x shellfind.py
echo -e $white" use python2 if you run main tools bro "
echo ""
sleep 2
echo -e $red" { Done Install bro } "
fi 

if [ $dwipan = 12 ] || [ $dwipan = 12 ]
then
clear
echo -e $blue" [ Installing sudo ] "
apt-get update && apt-get upgrade
apt-get install git
pkg install ncurses-utils
git clone https://github.com/widhi18/Termux-Sudo.git
cd Termux-Sudo
cat sudo > /data/data/com.termux/files/usr/bin/sudo
chmod 700 /data/data/com.termux/files/usr/bin/sudo
cd ~/
sleep 2
echo -e $red" { Done Install bro } "
fi


if [ $dwipan = 13 ] || [ $dwipan = 013 ] 
then
clear
echo -e $blue" [ Installing RED_HAWK ] "
sleep 2
apt-get update && apt-get upgrade 
apt get install git 
apt install php
git clone https://github.com/Tuhinshubhra/RED_HAWK
cd RED_HAWK
chmod +x *.php 
echo -e $white" if you run main tools , use php "
echo ""
sleep 2
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 14 ] || [ $dwipan = 014 ]
then
clear
echo -e $blue" [ Installing Kali-Nethunter ] "
sleep 2
echo -e $white" Sabar bro sambil ngopi :D "
apt update && apt upgrade
apt install git
git clone https://github.com/Hax4us/Nethunter-In-Termux.git
cd ~/Nethunter-In-Termux
chmod 777 kalinethunter
sh kalinethunter
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 15 ] || [ $dwipan = 015 ] 
then
clear
echo -e $blue" [ Installing hasher ] "
apt upgrade && apt update
apt-get install git
apt install python
apt install python2
git clone https://github.com/CiKu370/hasher.git
cd hasher
chmod +x hash.py
sleep 1
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 16 ] || [ $dwipan = 016 ] 
then
clear
echo -e $blue" [ Installing Weeman ] "
apt-get update && apt-get upgrade 
apt-get install git
apt install python2
git clone https://github.com/samyoyo/weeman
cd ~/weeman
pip2 install beautifulsoup
pip2 install bs4
cd ~/
echo -e $white" use ngrok bro if you phising your friends "
echo ""
sleep 2
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 17 ] || [ $dwipan = 017 ]
then
clear
echo -e $blue" [ Installing Mrcakil ] "
apt-get update && apt-get upgrade
apt-get install git
git clone https://github.com/mrcakil/Mrcakil.git
mv Mrcakil $HOME
cd ~/
cd Mrcakil 
chmod +x tools && tools2
echo ""
sleep 2
echo -e $white" usage ? ./tools "
echo ""
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 18 ] || [ $dwipan = 018 ] 
then
clear
echo -e $blue" [ Installing SpazSms & call tokopedia ] "
apt-get install git
apt install python
apt install php
git clone https://github.com/Gameye98/SpazSMS.git
echo ""
sleep 3
apt-get update && apt-get upgrade 
apt-get install git 
apt install python2
apt install curl 
git clone https://github.com/Senitopeng/SpamSms.git
echo ""
echo -e $white" Masuk ke cd nya dulu bro semangat bgt mau ngerjain :D "
sleep 3
echo ""
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 19 ] || [ $dwipan = 019 ]
then
clear
echo -e $blue"   [ Instaling websploit ] "
apt-get update && apt-get upgrade 
apt-get install git
apt install python && apt install python2
chmod +x websploit
sleep 0.6
echo -e $green" usage ? ./websploit or python2 "
echo ""
sleep 2
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 20 ] || [ $dwipan = 020 ] 
then
clear
echo -e $blue" [ Installing Script ] "
apt install python2
echo " ${red} pleas wait... "
sleep 3
echo " ${red} pleas wait... "
sleep 3
python2 dwipan.py
fi

if [ $dwipan = 21 ] || [ $dwipan = 021 ] 
then
clear
echo -e $blue" [ Installing fsociety ] "
apt-get update && apt-get upgrade
apt-get install git
apt install python
git clone https://github.com/manisso/fsociety
echo ""
sleep 1
echo -e $red" { Done Instaal bro } "
echo ""
sleep 1
echo -e $red" pleas wait... "
sleep 3
echo -e $red" pleas wait... "
sleep 3
cd fsociety
chmod fsociety.py
echo ""
sleep 0.5
echo -e $lightgreen" use python2 fsociety.py "
fi

if [ $dwipan = 22 ] || [ $dwipan = 022 ]
then
clear
echo -e $blue" [ Installing vbug ] "
sleep 2
echo ""
echo $red" pleas wait... "
unzip vbug.zip
cd vbug
chmod +x *.py
echo -e $lightgreen" use python2 if you run "
echo ""
sleep 1.4
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 23 ] || [ $dwipan = 023 ]
then
clear
echo -e $blue" [ Installing IPGeolocation ] "
apt-get update
apt-get install git
apt install python && apt install python2
git clone https://github.com/maldevel/IPGeolocation.git
cd IPGeolocation
chmod +x *.py
pip install -r requirements.txt
sleep 2
echo -e $okegreen" use python2 ipgeolocation.py bro if you run "
echo ""
sleep 3
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 24 ] || [ $dwipan = 024 ]
then
clear
echo $blue" [ Installing Instagram ] "
apt update
apt-get install git 
apt install python
git clone https://github.com/Pure-L0G1C/Instagram.git
cd Instagram
pip install -r requirements.txt
chmod +x *.py
echo "${green} python instagram.py <username> <wordlis> <threads> "
echo ""
echo "${green} (ex) python instagram.py <cikukba> <word1.txt> <16> "
sleep 3
echo -e $red" { Done Install bro } "
fi
