#!/bin/bash
#!/data/data/com.termux/files/usr/bin/bash
"""
I love my country Indonesia
autoinstaller DWIPANTARA
coded MR.R3DH3T
Don't copyright and recode this script bro
"""
#Warna // Color
blue='\e[0;34m'
cyan='\e[0;36m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'

#Start
function startingTools()
{
     clear
     echo -e "${okegreen}User : "$(uname -n)
     echo -e "${lightgreen}Login as : "$(whoami)
     echo -e "${okegreen}Starting Dwipantara tools at : "$(date)
     sleep 1
     echo " "
     
}
startingTools
#Bar
function spinner()
{
     sleep 3 &
     PID=$!
     i=1
     sp="/-\|"
     echo -n ' '
     while [ -d /proc/$PID ]
     do
       printf "\b${sp:i++%${#sp}:1}"
     done
}
function bar()
{
    bar=" ******************************************************"
    barlength=${#bar}
    i=0
    while ((i < 100)); do
        n=$((i*barlength / 100))
        printf "\e[00;32m\r[%-${barlength}s]\e[00m" "${bar:0:n}"
        ((i += RANDOM%5+2))
        sleep 0.02
    done
}


function CheckTools ()
{

   which wget > /dev/null 2>&1
   if [ "$?" -eq "0" ]; then
   echo -e $okegreen "[  Wget  ] Status : ${lighgreen}[ Installed ]"
   which wget > /dev/null 2>&1
   sleep 0.5
   else
   echo -e $red "[  Wget  ] Status : ${red}[ Not Installed ] "
   echo -e $yellow "[ ! ] Installing Wget "
   case $( uname -o ) in
   GNU/Linux)
   echo -e "${yellow}Installing Wget for PC"
   apt-get install wget -y;;
   Android)
   echo -e "${yellow}Installing Wgt for Termux"
   pkg install wget -y;;
   esac
   echo -e $okegreen "[  Wget  ] Done installing [ ✔ ]"
   which wget > /dev/null 2>&1
   sleep 0.5
   fi

   which curl > /dev/null 2>&1
   if [ "$?" -eq "0" ]; then
   echo -e $okegreen "[  Curl  ] Status : ${lighgreen}[ Installed ]"
   which curl > /dev/null 2>&1
   sleep 0.5
   else
   echo -e $red "[  Curl  ] Status : ${red}[ Not Installed ] "
   echo -e $yellow "[ ! ] Installing Curl "
   case $( uname -o ) in
   GNU/Linux)
   echo -e "${yellow}Installing Curl for PC"
   apt-get install curl -y;;
   Android)
   echo -e "${yellow}Installing Curl for Termux"
   pkg install curl -y;;
   esac
   echo -e $okegreen "[  Curl ] Done installing [ ✔ ]"
   which curl > /dev/null 2>&1
   sleep 0.5
   fi

   which git > /dev/null 2>&1
   if [ "$?" -eq "0" ]; then
   echo -e $okegreen "[  Git   ] Status : ${lighgreen}[ Installed ]"
   which git > /dev/null 2>&1
   sleep 1
   else
   echo -e $red "[  Git  ] Status : ${red}[ Not Installed ] "
   echo -e $yellow "[ ! ] Installing Git "
   case $( uname -o ) in
   GNU/Linux)
   echo -e "${yellow}Installing Git for PC"
   apt-get install git -y;;
   Android)
   echo -e "${yellow}Installing Git for Termux"
   pkg install git -y;;
   esac
   echo -e $okegreen "[  Git  ] Done installing [ ✔ ]"
   which curl > /dev/null 2>&1
   sleep 1
   fi

   echo " "
   echo -e $yellow"       [!]        Checking Tools 4 Termux       [!]"
   echo " "
   bar
   echo " "
   which python > /dev/null 2>&1
   if [ "$?" -eq "0" ]; then
   echo -e $okegreen "[ Python  ] Status : ${lighgreen}[ Installed ]"
   which python > /dev/null 2>&1
   sleep 0.5
   else
   echo -e $red "[ Python ] Status : ${red}[ Not Installed ] "
   echo -e $yellow "[ ! ] Installing Python For You [ ! ]"
   case $( uname -o ) in
   Android)
   pkg install python -y;;
   *)
   echo -e "${yellow}Your System is Not Termux ${red}[ x ]";;
   esac
   echo -e $okegreen "[ Python  ] Done installing [ ✔ ]"
   which python > /dev/null 2>&1
   sleep 0.5
   fi

   which python2 > /dev/null 2>&1
   if [ "$?" -eq "0" ]; then
   echo -e $okegreen "[ Python2 ] Status : ${lighgreen}[ Installed ]"
   which python2 > /dev/null 2>&1
   sleep 0.5
   else
   echo -e $red "[ Python2 ] Status : ${red}[ Not Installed ] "
   echo -e $yellow "[ ! ] Installing Python2 For You  [ ! ]"
   case $( uname -o ) in
   Android)
   pkg install python2 -y;;
   *)
   echo -e "${yellow}Your System is Not Termux";;
   esac
   echo -e $okegreen "[ Python2 ] Done installing [ ✔ ]"
   which curl > /dev/null 2>&1
   sleep 0.5
   fi

}
#Checking Internet Connection
echo -e "${yellow}Checking Internet Connection"
spinner
function checkinternet() 
{
  ping -c 1 google.com > /dev/null 2>&1
  if [[ "$?" != 0 ]]
  then
    echo -e $yellow "${red}NOT CONNECTED"
    echo
    echo -e $red "Run this Script, if you Connected to Internet"
    echo
    echo -e $red "Exit!"
    echo && sleep 2
    exit
  else
    echo -e $yellow "${okegreen}CONNECTED"
  fi
}

checkinternet
sleep 1
echo " "
echo -e $yellow"       [!]       Checking Tools       [!]"
echo " "
bar
echo " "
CheckTools
clear
####################################################
# CTRL C
####################################################
trap ctrl_c INT
ctrl_c () {
clear
echo -e $cyan" Terima Kasih Sudah Memakai Tools DWIPANTARA "
sleep 2
echo ""
echo -e $cyan" Dunia Itu Hanya Sesaat, Jadi Berbuatlah Baik Untuk Akhiratmu "
sleep 2
echo ""
echo -e $cyan" ├─   DWIPANTARA   ─┤" 
echo -e $cyan" ├─   Instagram    ─┤"
echo -e $cyan"         └─> dwi_pantara0518"
sleep 0.5
echo -e $cyan" ├─    Website     ─┤"
echo -e $cyan"         └─> https://dwipantara0518.blogspot.com/ "
sleep 1
echo -e $cyan" ├─     Author 1   ─┤ "
echo -e $cyan" ├─    MR.R3DH3T   ─┤ " 
echo -e $cyan" ├─    Instagram   ─┤ "
echo -e $cyan"          └─> naufalziidane_ "
echo -e $cyan" ├─     Author 2   ─┤ "
echo -e $cyan" ├─    loopstr34k  ─┤ " 
echo -e $cyan" ├─    Instagram   ─┤ "
echo -e $cyan"          └─> loopstr34k "
echo " "
echo -e $white" +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ "
echo -e $white" | 1.MsLq | 2.Ksatria Mujahidin | 3.mv24ky | 4.farhan | 5.root-S4D       | "
echo -e $white" | 6.greenhorn | 7.sasman96 | 8.mizuki | 9.nyi_iteung_ | 10.H Code       | "
echo -e $white" | 11.hanum_zaahra | 12.pribumi_jihad | 13.Lokzy | 14.Nc_tesla199        | "
echo -e $white" | 15.Opposite6890 | 16.B0C4HTU4N4K4L | 17.loopstr34k | 18.Emak_Julia    | "
echo -e $white" | 19.pasukan_hitam | 20.Niqabies_women | 21.A | 22._mushab_bin_umair    | "
echo -e $white" | 23.Hidayat | 24.farhan | 25.Dani | 26.rezim_laknat | 27.Squad_monkey3 | "
echo -e $white" | 28.p417ger4n_bers0rb4n | 29.d_dev05 | 30.Mr.Cl4Y | 31.jurnal_jamaah   | "
echo -e $white" +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ "
echo ""
sleep 2
read enter
exit
}


echo -e $red"   ______        _____ ____   _    _   _ _____  _    ____      _ "
echo -e $red"  |  _ \ \      / /_ _|  _ \ / \  | \ | |_   _|/ \  |  _ \    / \ "
echo -e $red"  | | | \ \ /\ / / | || |_) / _ \ |  \| | | | / _ \ | |_) |  / _ \ "
echo -e $red"  | |_| |\ V  V /  | ||  __/ ___ \| |\  | | |/ ___ \|  _ <  / ___ \ "
echo -e $red"  |____/  \_/\_/  |___|_| /_/   \_\_| \_| |_/_/   \_\_| \_\/_/   \_\ "
echo ""
echo -e $white"        ___ _   _ ____   ___  _   _ _____ ____ ___    _ "
echo -e $white"       |_ _| \ | |  _ \ / _ \| \ | | ____/ ___|_ _|  / \ "
echo -e $white"        | ||  \| | | | | | | |  \| |  _| \___ \| |  / _ \ "
echo -e $white"        | || |\  | |_| | |_| | |\  | |___ ___) | | / ___ \ "
echo -e $white"       |___|_| \_|____/ \___/|_| \_|_____|____/___/_/   \_\ "
echo ""
sleep 2
clear
function firsttools() {
echo -e "${yellow}Alert!"
echo -e "${yellow}Any = Linux PC        |   N = Next tools      |   Version   |"
echo -e "${yellow}GNU/Linux = Linux PC  |   P = Prev tools      |             |"
echo -e "${yellow}Android = Termux      |   C = Contact Author  |     2.3     |"
echo -e $red"+-----+--------------------------------------+-----------------------+"
sleep 0.1
echo -e $red"| Num |        Tools Name        [Tested On] |    Function           |"
sleep 0.1
echo -e $red"+-----+--------------------------------------+-----------------------+"
sleep 0.1
echo -e $red"|  1  |     Metasploit Framework       [Any] | Pentesting            |"
sleep 0.1
echo -e $red"|  2  |     Torshammer                 [Any] | DDOS                  |"
sleep 0.1
echo -e $red"|  3  |     Xerxes                     [Any] | DDOS                  |"
sleep 0.01  
echo -e $red"|  4  |     SQLMap                     [Any] | Get Database          |"
sleep 0.1 
echo -e $red"|  5  |     Termux Ohmyzhs         [Android] | Termux Theme          |"
sleep 0.01
echo -e $red"|  6  |     ko-dork                    [Any] | Pentesting Web        |"
sleep 0.1  
echo -e $red"|  7  |     CMSmap                     [Any] | CMS Scanner           |"
sleep 0.1
echo -e $red"|  8  |     Ngrok                      [Any] | Go Online             |"
sleep 0.01
echo -e $red"|  9  |     Webdav                     [Any] | Web Server            |"
sleep 0.1
echo -e $red"|  10 |     Venom                      [Any] | Pentesting            |"
sleep 0.1
echo -e $red"|  11 |     Shell Finder               [Any] | Databse Web           |"
sleep 0.01
echo -e $red"|  12 |     Termux Sudo            [Android] | Access Root           |"
sleep 0.1
echo -e $red"|  13 |     Red Hawk                   [Any] | Scanning Web          |"
sleep 0.1
echo -e $red"|  14 |     Kali Nethunter         [Android] | OS Kali Linux         |"
sleep 0.1
echo -e $red"|  15 |     Hasher                     [Any] | Hashing               |"
sleep 0.1
echo -e $red"|  16 |     Weeman                     [Any] | Pishing               |"
sleep 0.1
echo -e $red"|  17 |     Mercury                    [Any] | Pentesting            |"
sleep 0.1
echo -e $red"|  18 |     SpazSMS                    [Any] | Spam SMS              |"
sleep 0.1
echo -e $red"|  19 |     Websploit                  [Any] | Pentesting & MLITM    |"
sleep 0.1
echo -e $red"|  20 |     Script Deface              [Any] | Creator Script        |"
sleep 0.1
echo -e $red"|  21 |     Fsociety                   [Any] | Pentesting            |"
sleep 0.1 
echo -e $red"|  22 |     Vbug                       [Any] | Virtual Bug           |"
sleep 0.1  
echo -e $red"|  23 |     IP Geolocation             [Any] | Tracking IP           |"
sleep 0.1
echo -e $red"|  24 |     Instagram                  [Any] | Brute Force           |"
sleep 0.1
echo -e $red"|  25 |     User Recon                 [Any] | Scan Username         |"
echo -e $red"+-----+--------------------------------------+-----------------------+"
sleep 0.1
}
function secondtools() {
echo -e "${yellow}Alert!"
echo -e "${yellow}Any = Linux PC        |   N = Next tools      |   Version   |"
echo -e "${yellow}GNU/Linux = Linux PC  |   P = Prev tools      |             |"
echo -e "${yellow}Android = Termux      |   C = Contact Author  |     2.3     |"
echo -e $red"+-----+--------------------------------------+-----------------------+"
sleep 0.1
echo -e $red"| Num |        Tools Name        [Tested On] |    Function           |"
sleep 0.1
echo -e $red"+-----+--------------------------------------+-----------------------+"
sleep 0.1
echo -e $red"|  26 |     The Fat Rat          [GNU/Linux] | Pentesting            |"
sleep 0.1
echo -e $red"|  27 |     Evil - Droid         [GNU/Linux] | Payload Android       |"
sleep 0.1
echo -e $red"|  28 |     Wifi Jammer          [GNU/Linux] | Wlan Attack           |"
sleep 0.1
echo -e $red"|  29 |     Hydra                      [Any] | Password Attack       |"
sleep 0.1
echo -e $red"|  30 |     Nmap                       [Any] | Information Gathering |"
sleep 0.1
echo -e $red"|  31 |     Wordprescan                [Any] | Wp-login & password   |"
sleep 0.1
echo -e $red"|  32 |     Theharverster              [Any] | Searching Any email   |"
sleep 0.1
echo -e $red"|  33 |     Inetspeedtest              [Any] | Check Speed Internet  |"
sleep 0.1
echo -e $red"|  34 |     Termux-Packages        [Android] | Command tools termux  |"
sleep 0.1 
echo -e $red"|  35 |     Ubuntu                 [Android] | OS Ubuntu             |"
sleep 0.1
echo -e $red"|  36 |     Routersploit         [GNU/Linux] | Router attack         |"
sleep 0.1
echo -e $red"|  37 |     Joomscan             [GNU/Linux] | Scanning Web CMS      |"
sleep 0.1
echo -e $red"|  38 |     Pybelt                     [Any] | Scanning Vuln Web     |"
sleep 0.1
echo -e $red"|  39 |     Brute XSS                  [Any] | Pentesting Web        |"
sleep 0.1
echo -e $red"|  40 |     Dirsearch                  [Any] | Search Direktory Web  |"
sleep 0.1 
echo -e $red"|  41 |     WebApp                     [Any] | Information Grather   |"
sleep 0.1
echo -e $red"|  42 |     Hunner                     [Any] | Any Bruteforce & Scan |"
sleep 0.1
echo -e $red"|  43 |     Netattack2           [GNU/Linux] | Wlan attack & Kick    |"
sleep 0.1
echo -e $red"|  44 |     Wifiphisher          [GNU/Linux] | Simple Wlan attack    |"
sleep 0.1
echo -e $red"|  45 |     Wifigod              [GNU/Linux] | Simple Wlan attack    |"
sleep 0.1
echo -e $red"|  46 |     Th3inspector               [Any] | Special for any search|"
sleep 0.1
echo -e $red"|  47 |     Xattacker                  [Any] | Pentesting web        |"
sleep 0.1
echo -e $red"|  48 |     Darksploit                 [Any] | Pentesting            |"
sleep 0.1
echo -e $red"|  49 |     PTF                  [GNU/Linux] | Peneration Framework  |"
sleep 0.1
echo -e $red"|  50 |     IMSI-Catcher Detector  [Android] | Protect your self     |"
sleep 0.1
echo -e $red"+-----+--------------------------------------+-----------------------+"
sleep 0.1
echo -e $red"|  00 |     Exit Dwipantara Tools            | ${yellow}Good Bye              ${red}|"
sleep 0.1
echo -e $red"+-----+--------------------------------------+-----------------------+"
sleep 0.01
}
firsttools
echo ""
while true; do
read -p" root@dwipantara ~/# " dwipan;

if [ $dwipan = n ] || [ $dwipan = N ]
then
secondtools
fi
if [ $dwipan = p ] || [ $dwipan = P ]
then
firsttools
fi

if [ $dwipan = c ] || [ $dwipan = C ]
then
clear
echo " "
echo -e $red      "         [ Contact Author ]"
echo " "
echo -e $okegreen "     Author 1   ▶    MR.R3DH3T"
echo -e $okegreen "     Instagram  ▶    naufalziidane_"
echo -e $red      "------------------------------------------------"
echo -e $blue     "     Author 2   ▶    LOOPSTR34K"
echo -e $blue     "     Instagram  ▶    loopstr34k"
echo -e $blue     "     Telegram   ▶    https://t.me/Grandshoot"
echo " "
exit
fi

if [ $dwipan = 1 ] || [ $dwipan = 01 ]
then
clear
echo -e $blue" [ Installing Metasploit ] "
sleep 1
echo " Harus Sabar! "
sleep 3
apt install curl -y
wget https://raw.githubusercontent.com/Hax4us/Metasploit_termux/master/metasploit.sh
sleep 1
chmod +x metasploit.sh
./metasploit.sh
sleep 5
mv metasploit-framework $HOME
echo "${green} Use Command 'msfconsole' to run metasploit "
echo "${green} e.g: root@dwipantara#~/ msfconsole"
sleep 2
echo -e $red" { Done Install bro } "
fi


if [ $dwipan = 0 ] || [ $dwipan = 00 ] 
then
clear
echo -e $okegreen">>  Pesan terakhir! << "
echo ""
echo ""
sleep 2
echo -e $lightgreen" Jangan pernah tinggalin ngaji ingat! menuntut ilmu agama itu wajib , karna jaman sekarang orang islam tidak tahu agamanya sendiri "
echo ""
sleep 3
echo -e $red" Jangan pacaran mulu! , Jika kamu diam saat agamamu dihina gantilah pakaianmu dengan kain kafan "
echo ""
sleep 3
echo -e $red" Islam bagaikan buih di lautan ( Banyak orang islam tapi tidak tahu islam yang sesungguhnya ) "
echo ""
sleep 3
echo -e $okegreen" Semangat Berjuang Demi Membela Kebenaran! TAKBIR! " 
echo ""
sleep 3
echo -e $lightgreen" Per eratlah tali persaudaraan , wa alfu minkum wassalamu'alaikum warrohmatullohi wabarokatuhu "
echo ""
sleep 3
exit
fi

if [ $dwipan = 2 ] || [ $dwipan = 02 ]
then 
clear
echo -e $blue" [ Installing Torshammer ] "
git clone https://github.com/cyweb/hammer.git
cd hammer
chmod +x hammer.py
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 3 ] || [ $dwipan = 03 ]
then
clear
echo -e $blue" [ Installing Xerxes ] "
echo -e "${yellow}Installing Clang for Xerxes ${red}[ ! ]"
function insclang ()
{
     case $( uname -o ) in
     GNU/Linux)
     apt-get install clang -y
     echo -e "${okegreen}Finish [ ✔ ]";;
     Android)
     pkg install clang -y
     echo -e "${okegreen}Finish [ ✔ ]";;
     esac
     
}
insclang

echo -e $yellow "  [i]  Downloading Xerxes!  [i]"

down &
pid=$!
for i in `seq 1 100`;
do
    load $i
    sleep 0.1
done
kill $pid > /dev/null 2>&1
sleep 1
echo ""
git clone https://github.com/zanyarjamal/xerxes.git 2> /dev/null
echo -e $yellow "  [i]  Setting Up Xerxes Tools  [i]"
setuptools &

sleep 5

kill "$!"
printf '\n'
cd xerxes
gcc xerxes.c -o xerxes
echo " use ?  ./xerxes target (ex) www.suaranasional.com 80 , jika tidak ada tulisan voly sent ulang aja bro "
echo ""
echo ""
sleep 2
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 4 ] || [ $dwipan = 04 ] 
then
clear
echo -$blue" [ Installing SQLmap-dev ] "
git clone --depth 1 https://github.com/sqlmapproject/sqlmap.git sqlmap-dev
cd sqlmap-dev
chmod +x *.py
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 5 ] || [ $dwipan = 05 ]
then
clear
echo -e $blue" [ Installing Termux-ohmyzsh ] "
sh -c "$(curl -fsSL https://github.com/Cabbagec/termux-ohmyzsh/raw/master/install.sh)"
~/.termux/colors.sh
echo -e $white" ganti color ? ketik ~/.termux/colors.sh "
sleep 2
echo ""
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 6 ] || [ $dwipan = 06 ]
then
clear
echo -e $blue" [ Installing ko-dork ] "
git clone https://github.com/ciku370/ko-dork.git
mv ko-dork $HOME
cd ~/
cd ko-dork
chmod +x *.py
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 7 ] || [ $dwipan = 07 ]
then
clear
echo -e $blue" [ Installing CMS scanner ] "
git clone https://github.com/Dionach/CMSmap.git
sleep 1
cd CMSmap
chmod +x cmsmap.py
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 8 ] || [ $dwipan = 08 ]
then
clear
echo -e $red" [ Installing Ngrok ] "
mkdir ngrok
cd ~/ngrok
echo -e "${red} (1) 32 bit"
echo -e "${red} (2) 64 bit"
echo -e "${red} (3) ARM"
read -p " root@dwipantara#~/ngrok-installer/ " ngrok;
  if [ $ngrok = 1 ] || [ $ngrok = 01 ]
  then
  echo -e $yellow"Download Ngrok 32 bit "
  wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip
  unzip ngrok-stable-linux-386.zip
  echo $yellow"Use Command './ngrok http 80' to use Ngrok"
  echo $yellow"e.g: root@dwipantara#~/ ngrok http 80"
  exit
  fi
  if [ $ngrok = 2 ] || [ $ngrok = 02 ]
  then
  echo -e $yellow"Download Ngrok 64 bit "
  wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
  unzip ngrok-stable-linux-amd64.zip
  echo $yellow"Use Command './ngrok http 80' to use Ngrok"
  echo $yellow"e.g: root@dwipantara#~/ ngrok http 80"
  exit
  fi
  if [ $ngrok = 3 ] || [ $ngrok = 03 ]
  then
  echo -e $yellow"Download Ngrok ARM "
  wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip
  unzip ngrok-stable-linux-arm.zip
  echo -e $yellow"Use Command './ngrok http 80' to use Ngrok"
  echo -e $yellow"e.g: root@dwipantara#~/ ngrok http 80"
  exit
  fi

cd ~/
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 9 ] || [ $dwipan = 09 ] 
then
clear
echo -e $blue" [ Installing Webdav ] "
function reqweb ()
{
     echo -e "${yellow}Installing Requirements Webdav"
     case $( uname -o ) in
     Android)
     pip2 install urllib3 chardet certifi idna requests
     apt install openssl curl
     pkg install libcurl;;
     GNU/Linux)
     pip install urllib3 chardet certifi idna requests
     apt-get --force-yes -y install openssl curl libcurl3
     echo -e "${okegreen}Finish Installing Requirements Webdav [ ✔ ]"
     esac
}
reqweb    
mkdir webdav/
cd webdav
wget https://pastebin.com/raw/HnVyQPtR -O webdav.py
chmod 777 webdav.py
cd 
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 10 ] || [ $dwipan = 010 ] 
then
clear
echo -e $blue" [ Installing venom ] "
sleep 2
git clone https://github.com/r00t-3xp10it/venom.git
cd venom
sudo chmod -R +x *.sh
sudo chmod -R +x *.py
cd aux
sudo ./setup.sh
echo -e $white" install metasploit dulu bro error kan "
sleep 2
echo ""
echo -e $white" if you run main tools , use msfvenom -h "
sleep 3
echo ""
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 11 ] || [ $dwipan = 011 ]
then
clear
echo -e $blue" [ Installing Shell-finder ] "
git clone https://github.com/bhavyanshu/Shell-Finder.git
cd Shell-Finder
chmod +x shellfind.py
echo -e $white" use python2 and python if you run main tools bro "
echo -e $yellow"       └>termux   └> GNU/Linux (PC)"
echo  " "
sleep 2
echo -e $red" { Done Install bro } "
fi 

if [ $dwipan = 12 ] || [ $dwipan = 012 ]
then
clear
echo -e $blue" [ Installing sudo for Termux ] "
function sudooo()
{
     case $( uname -o ) in
     Android)
     apt upgrade
     pkg install ncurses-utils
     git clone https://github.com/widhi18/Termux-Sudo.git
     cd Termux-Sudo
     cat sudo > /data/data/com.termux/files/usr/bin/sudo
     chmod 700 /data/data/com.termux/files/usr/bin/sudo
     cd;;
     GNU/Linux)
     echo -e "${red}Your OS is Not Termux"
     exit;;
     esac
}
sudooo
sleep 2
echo -e $red" { Done Install bro } "
fi


if [ $dwipan = 13 ] || [ $dwipan = 013 ] 
then
clear
echo -e $blue" [ Installing RED_HAWK ] "
sleep 2
echo " "
echo -e "${blue}Installing Requirement RED_HAWK"
function instphp()
{
     case $( uname -o ) in
     Android)
     pkg install php -y;;
     GNU/Linux)
     apt-get install php -y;;
     esac
}
instphp
git clone https://github.com/Tuhinshubhra/RED_HAWK
cd RED_HAWK
chmod +x *.php 
echo -e $white" if you run main tools , use php "
echo ""
sleep 2
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 14 ] || [ $dwipan = 014 ]
then
clear
echo -e $blue" [ Installing Kali-Nethunter ] "
sleep 2
echo -e $white" Sabar bro sambil ngopi :D "
function nethunter()
{
     case $( uname -o ) in
     Android)
     apt upgrade
     git clone https://github.com/Hax4us/Nethunter-In-Termux.git
     cd /Nethunter-In-Termux
     chmod 777 kalinethunter
     sh kalinethunter;;
     *)
     echo -e "${cyan}Just For Termux"
     esac
}
nethunter
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 15 ] || [ $dwipan = 015 ] 
then
clear
echo -e $blue" [ Installing hasher ] "
git clone https://github.com/CiKu370/hasher.git
cd hasher
chmod +x hash.py
sleep 1
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 16 ] || [ $dwipan = 016 ] 
then
clear
echo -e $blue" [ Installing Weeman ] "
git clone https://github.com/samyoyo/weeman
cd weeman
function reqweeman()
{
       echo -e "${yellow}Installing Requirements Weeman"
       case $( uname -o ) in
       Android)
       pip2 install beautifulsoup
       pip2 install bs4;;
       GNU/Linux)
       pip install beutifulsoup
       pip install bs4;;
       esac
       
       
}
reqweeman
echo -e "${blue}Done."
cd
echo -e $white "use ngrok bro if you phising your friends "
echo ""
sleep 2
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 17 ] || [ $dwipan = 017 ]
then
clear
echo -e $blue" [ Installing Mercury ] "
git clone https://github.com/MetaChar/Mercury.git
function reqMer()
{
  case $(uname -o) in
  Android)
  cd Mercury
  pip2 install -r rerquirements.txt;;
  GNU/Linux)
  cd Mercury
  pip install -e requirements.txt;;
  esac
}
reqMer
cd Mercury
chmod +x Mercury.py
echo -e $white" use python2 and python for run Mercury Tools"
echo -e $yellow"       └>termux   └> GNU/Linux (PC)"
echo  " "
sleep 3
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 18 ] || [ $dwipan = 018 ] 
then
clear
echo -e $blue" [ Installing SpazSms & call tokopedia ] "
function reqsms()
{
    case $( uname -o ) in
    Android)
    pkg install php;;
    GNU/Linux)
    apt-get install php -y;;
    esac
}
reqsms
git clone https://github.com/Gameye98/SpazSMS.git
echo ""
sleep 1.5
git clone https://github.com/Senitopeng/SpamSms.git
echo ""
echo -e $white" This tools for Number Indonesian "
sleep 1.5
echo ""
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 19 ] || [ $dwipan = 019 ]
then
clear
echo -e $blue"   [ Instaling websploit ] "
pip2 install request
pip2 install scapy
pip install --upgrade pip
git clone https://github.com/websploit/websploit.git
cd websploit
chmod +x websploit
sleep 0.6
echo -e $green" usage ? ./websploit or python2 websploit "
echo ""
sleep 2
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 20 ] || [ $dwipan = 020 ] 
then
clear
echo -e $blue" [ Installing Script ] "
echo " ${red} pleas wait... "
sleep 3
python2 dwipan.py
fi

if [ $dwipan = 21 ] || [ $dwipan = 021 ] 
then
clear
echo -e $blue" [ Installing fsociety ] "
git clone https://github.com/manisso/fsociety
cd fsociety
chmod a+x *.py
cd ~/
echo ""
sleep 1
echo -e $red" { Done Instaal bro } "
echo ""
sleep 1
cd fsociety
chmod +x fsociety.py
echo ""
sleep 0.5
echo -e $lightgreen" use python2 fsociety.py "
fi

if [ $dwipan = 22 ] || [ $dwipan = 022 ]
then
clear
echo -e $blue" [ Installing vbug ] "
sleep 2
echo ""
echo $red" pleas wait... "
unzip vbug.zip
cd vbug
chmod +x *.py
echo -e $lightgreen" use python2 and python for run this tool "
echo -e "${yellow}         └> termux   └> GNU/Linux PC"
echo " " 
sleep 1.4
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 23 ] || [ $dwipan = 023 ]
then
clear
echo -e $blue" [ Installing IPGeolocation ] "
git clone https://github.com/maldevel/IPGeolocation.git
cd IPGeolocation
chmod +x *.py
function pip1pip2()
{
   case $( uname -o ) in
   GNU/Linux)
   pip install -r requirements.txt;;
   Android)
   pip2 install -r requirements.txt;;
   esac
}
pip1pip2
sleep 2
echo -e $okegreen" use python2 and python ipgeolocation.py bro if you run "
echo -e "${yellow}       └> termux   └> GNU/Linux PC"
echo ""
sleep 3
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 24 ] || [ $dwipan = 024 ]
then
clear
echo -e $blue" [ Installing Instagram ] "
git clone https://github.com/Pure-L0G1C/Instagram.git
cd Instagram
pip install -r requirements.txt
chmod +x *.py
echo -e "${green} python instagram.py <username> <wordlis> <threads> "
echo ""
echo -e "${green} (ex) python instagram.py cikukba wordlist.txt 16 "
sleep 3
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 25 ] || [ $dwipan = 025 ]
then
clear
echo -e "${blue}[ Installing User Recon ]"
git clone https://github.com/thelinuxchoice/userrecon.git
cd userrecon
chmod +x userrecon.sh
echo -e $okegreen"{ Done Install }"
fi

if [ $dwipan = 26 ] || [ $dwipan = 026 ]
then
clear
echo -e $blue"[ Installing The Fat Rat ]"
git clone https://github.com/Screetsec/TheFatRat.git
cd TheFatRat
chmod +x setup.sh && ./setup.sh
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 27 ] || [ $dwipan = 027 ]
then
clear
echo -e $okegreen"[ Installing Evil - Droid ]"
echo -e $red"[!]  Generate Payload For Backdoor Android  [!]"
git clone https://github.com/M4sc3r4n0/Evil-Droid.git
cd Evil-Droid
chmod +x evil-droid
echo -e $red" { Done Install } "
fi

if [ $dwipan = 28 ] || [ $dwipan = 028 ]
then
clear
echo -e $blue"[ Installing Wifi Jammer ]"
git clone https://github.com/DanMcInerney/wifijammer.git
cd wifijammer
chmod +x wifijammer.py
fi

if [ $dwipan = 29 ] || [ $dwipan = 029 ]
then
clear
echo -e $blue"[ Installing Hydra ]"
apt install update && apt upgrade
apt install hydra 
echo ""
echo -e $red" pleas wait... "
sleep 1
echo -e $red" pleas wait... "
sleep 1
echo -e $red" pleas wait... "
sleep 2
echo ""
mkdir wordlist 
cd wordlist 
wget http://scrapmaker.com/download/data/wordlists/dictionaries/rockyou.txt
cd ~/
echo ${okegreen}" use hydra -h for help "
echo ""
echo ${okegreen}" This for ssh admin or root { e.g } hydra -t 4 127.0.0.1 ssh -l username -P wordlist.txt -s 22 -vV "
fi

if [ $dwipan = 30 ] || [ $dwipan = 030 ]
then
clear
echo -e $blue"[ Installing Nmap ] "
apt update && apt upgrade
apt install nmap
echo ""
echo -e $red" pleas wait... "
sleep 0.5
echo -e $red" pleas wait... "
sleep 0.5
echo -e $red" pleas wait... "
sleep 2
echo ""
echo ${okegreen}" { e.g } nmap 127.1.0.0 -sV "
echo ""
echo -e $red" { Done Install bro } "
fi


if  [ $dwipan = 31 ] || [ $dwipan = 031 ] 
then
clear
echo -e $blue" [ Installing WPscan ] "
apt install ruby -y
git clone https://github.com/wpscanteam/wpscan.git
echo ""
echo -e $red" ALERT! Don't close . "
sleep 4
gem install bundle
bundle install config build.nokogiri --use-system-libraries
gem install wpscan
bundle install && rake install 
echo ${okegreen}" { e.g } wpscan -h "
echo ""
echo ${okegreen}" { e.g } wpscan --url http://kapanlobisa.co.id --enumerate u "
echo ""
sleep 2
echo ${okegreen}" { e.g } wpscan --url http://kapanlobisa.co.id --wordlist wordlist.txt --username input admin wordpress "
sleep 2
echo ""
echo -e $red" { Done Install bro } "
fi


if [ $dwipan = 32 ] || [ $dwipan = 032 ]
then
clear
echo -e $blue" [ Installing Theharvester ] "
git clone https://github.com/laramies/theHarvester.git 2> /dev/null
sleep 2
cd theHarvester
chmod +x *.py
echo -e "${red}{ Done Installing The Harvester }"
fi

if [ $dwipan = 33 ] || [ $dwipan = 033 ] 
then
clear
echo -e $blue" [ Installing Inetspeedtest ] "
git clone https://github.com/loopstr34k/Inetspeedtest.git
cd Inetspeedtest
pip install -r requirements.txt
sleep 2
echo "${okegreen} Use python2 inetspeedtest if you check speed your internet "
echo ""
echo -e $red" { Done Install } "
fi

if [ $dwipan = 34 ] || [ $dwipan = 034 ]
then
clear
echo -e $blue" [ Installling Termux-Packages ] "
apt update && apt upgrade 
git clone https://github.com/termux/termux-packages.git 
echo ""
echo "${okegreen} If you look command or install  all for termux open cd termux-packages/packages "
echo ""
sleep 4
echo -e $red" { Done Install } "
fi

if [ $dwipan = 35 ] || [ $dwipan = 035 ] 
then
clear
echo -e $blue" [ Instaling Ubuntu ] "
apt update && apt upgrade
apt install wget
apt install proot
git clone https://github.com/Neo-Oli/termux-ubuntu.git
cd ~/termux-ubuntu
chmod a+x ubuntu.sh
sh ubuntu.sh
echo "${red} please wait ... "
sleep 3
echo ""
echo "${okegreen} use nano /data/data/com.termux/files/home/Dwipantara/termux-ubuntu/ubuntu-fs/etc/resolv.conf | nameserver 8.8.8.8 "
echo "${red} { Done } "
fi

if [ $dwipan = 36 ] || [ $dwipan = 036 ] 
then
clear
echo -e $blue" [ Installing Routersploit ] "
apt update
apt-get install python3-pip
git clone https://www.github.com/threat9/routersploit.git
cd routersploit
python3 -m pip install -r requirements.txt
echo "${okegreen} Use Python3 if you run Routersploit "
echo ""
sleep 2
echo -e $red" { Done Install } "
fi

if [ $dwipan = 37 ] || [ $dwipan = 037 ]
then
clear
echo -e $blue" [ Installing Joomscan ] "
apt update 
apt-get install perl 
git clone https://github.com/rezasp/joomscan.git
cd joomscan
chmod a+x *.pl
echo "${okegreen} Use perl joomscan.pl "
echo ""
echo -e $red" { Done Install } "
fi

if [ $dwipan = 38 ] || [ $dwipan = 038 ] 
then
clear
echo -e $blue" [ Installing Pybelt ] "
apt update
git clone https://github.com/Ekultek/Pybelt.git
cd Pybelt
pip install -r requirements.txt
sleep 3
echo "${okegreen} Use python2 pybelt.py or python pybelt.py "
echo -e "${yellow}      └> termux        └> GNU/Linux PC "
echo ""
echo -e $red" { Done Install } "
fi

if [ $dwipan = 39 ] || [ $dwipan = 039 ]
then
clear
echo -e $blue" [ Installing BruteXSS ] "
apt update 
git clone https://github.com/ihamquentin/BruteXSS.git
cd BruteXSS
chmod a+x *.py
echo "${okegreen} Use python2 brutexss.py "
echo ""
echo -e $red" { Done Install } "
fi

if [ $dwipan = 40 ] || [ $dwipan = 040 ]
then
clear
echo -e $blue" [ Installing Dirserach ] "
apt update 
git clone https://github.com/maurosoria/dirsearch.git
cd dirsearch
chmod a+x *.py
cd ~/
echo "${okegreen} This tools cool for Defacer "
sleep 2
echo ""
echo -e $red" { Done Install } "
fi

if [ $dwipan = 41 ] || [ $dwipan = 041 ] 
then
clear
echo -e $blue" [ Installing WebApp ] "
apt update 
git clone https://github.com/jekyc/wig.git
cd wig 
chmod a+x *.py
echo ""
echo "${okegreen} If run this tools on termux , Use python3 wig.py example.com "
sleep 4
echo""
echo -e $red" { Done Install } "
fi

if [ $dwipan = 42 ] || [ $dwipan = 042 ]
then
clear
echo -e $blue" [ Installing Hunner ] "
apt update
git clone https://github.com/b3-v3r/Hunner.git
cd Hunner
chmod a+x *.py
cd ~/
echo""
echo -e $red" { Done Install } "
fi

if [ $dwipan = 43 ] || [ $dwipan = 043 ]
then
clear
echo -e $blue" [ Installing Netattack2 ] "
apt update
git clone https://github.com/wi-fi-analyzer/netattack2.git
cd netattack2
apt-get install python-nmap python-argparse python-scapy iw
chmod a+x *.py
cd ~/
echo""
echo -e $red" { Done Install } "
fi

if [ $dwipan = 44 ] || [ $dwipan = 044 ]
then
clear
echo -e $blue" [ Installing Wifiphisher ] "
apt update 
https://github.com/wifiphisher/wifiphisher.git
cd wifiphisher
chmod a+x *.py
sudo python setup.py install
echo "${okegreen} Runing main tools command : wifiphisher or python bin/wifiphisher . "
echo""
echo -e $red" { Done Install } "
fi

if [ $dwipan = 45 ] || [ $dwipan = 045 ] 
then
clear
echo -e $blue" [ Installing Wifigod ] "
apt update 
git clone https://github.com/blackholesec/wifigod.git
cd wifigod
chmod a+x *.py
echo""
echo -e $red" { Done Install } "
fi

if [ $dwipan = 46 ] || [ $dwipan = 046 ]
then
clear
echo -e "${blue} [ Installing Th3inspector ] "
function inspector()
{
   case $( uname -o ) in
   Android)
   apt update && apt upgrade
   pip2 install scapy;;
   GNU/Linux)
   pip install scapy;;
   esac
}
inspector
echo -e $okegreen" Done Install Requirements Inspector [ ✔ ] "
sleep 3
git clone https://github.com/Moham3dRiahi/Th3inspector.git
sleep 1
cd Th3inspector
chmod +x install.sh && ./install.sh
cd ~/
echo""
echo -e "${okegreen} Use perl For Run Main Tools ; perl Th3inspector.pl "
echo -e $red" { Done Install } "
fi

if [ $dwipan = 47 ] || [ $dwipan = 047 ] 
then
clear
echo -e $blue" [ Installing Xattacker ] "
function attack()
{
	case $( uname -o ) in
	Android)
	apt update && apt upgrade
	apt install perl
	git clone https://github.com/Moham3dRiahi/XAttacker.git
	cd XAttacker
	chmod +x termux-install.sh
	chmod a+x *.pl
	bash termux-install.sh;;
	GNU/Linux)
	git clone https://github.com/Moham3dRiahi/XAttacker.git
	cd XAttacker
	chmod a+x *.pl;;
	esac
}
attack
sleep 2.5
echo -e "${okegreen} Done Install Requirements Xattacker [ ✔ ] "
cd ~/
echo""
echo -e "${okegreen} Use perl For Run Main Tools ; perl XAttacker.pl "
echo""
echo -e "${red} { Done Install } "
fi

if [ $dwipan = 48 ] || [ $dwipan = 048 ] 
then
clear
echo -e "${blue} [ Installing DarkSploit ] "
function darkpo()
{
	case $( uname -o ) in
	Android)
	apt update && apt upgrade
	sleep 2
	pip install -r requirements.txt
	echo -e "${okegreen} Done Install Requirements Dark [ ✔ ] ";;
	GNU/Linux)
	pip2 install -r requirements.txt
	echo -e "${okegreen} Done Install Requirements DarkSploit [ ✔ ] ";;
	esac
}
git clone https://github.com/anthrax3/DarkSploit.git
sleep 0.1
cd DarkSploit
./installgnuroot
darkpo
cd ~/
echo""
echo -e "${red} { Done Install } "
fi

if [ $dwipan = 49 ] || [ $dwipan = 049 ] 
then
clear
echo -e "${blue} [ Installing PTF ] "
git clone https://github.com/trustedsec/ptf.git
chmod a+x ptf
echo""
echo -e "${okegreen} Run Main Tools : ./ptf "
echo""
echo -e "${red} { Done Install } "
fi

if [ $dwipan = 50 ] || [ $dwipan = 050 ]
then
clear
echo -e "${blue} [ Download AIMSICD ] "
echo""
echo -e "${okegreen} This tools For protect your self from Hacker , Fake tower call . "
echo -e "${okegreen} Because Hacker and tower call stole information on Your device . "
sleep 2
echo -e "${yellow} Copy This Link if you Downloads this apk "
echo""
echo -e "${yellow} https://sfile.mobi/5CFBrs7xIsU "
sleep 2
echo -e "${red} { If You protect Your Self Donwload This apk } "
fi

done
